-- CONVERT NAME FORMAT FROM: "last, first" to "First Last"

CONCAT(
			CONCAT(UPPER(
					LEFT(TRIM((SUBSTRING_INDEX(CUSTOMER_NAME,",",-1))
					),1)),
			RIGHT(
				SUBSTRING_INDEX(CUSTOMER_NAME,",",-1),
				LENGTH(SUBSTRING_INDEX(CUSTOMER_NAME,",",-1))-2))," ",
			CONCAT(UPPER(
					LEFT(TRIM((SUBSTRING_INDEX(CUSTOMER_NAME,",",1))
					),1)),
			RIGHT(
				(SUBSTRING_INDEX(CUSTOMER_NAME,",",1)),
				LENGTH(SUBSTRING_INDEX(CUSTOMER_NAME,",",1))-1)))
			AS FULL_NAME,
